### ISSUE TITLE
企業微信上顯示不全

### ISSUE THREAD

**Issue by keney2023** [Yanyutin753/googleSearch-On-Wechat#1]
企業微信上搜索總結看不到有有超鏈接，只有文字結果
![微信截图_20231115104322](https://github.com/Yanyutin753/googleSearch-On-Wechat/assets/134574829/359a420b-60d8-44d2-9111-2fb66d888f21)
但是後台看是有超鏈接的
![图片](https://github.com/Yanyutin753/googleSearch-On-Wechat/assets/134574829/e2bf1d3c-97cb-48cf-a29f-d28cebc9af60)

**Comment by Yanyutin753** [comment]
这个的话，可能是chatGpt总结的问题，你可以去改改文件里面对chatGpt的人设，就让他把链接也给发上来



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: keney2023 ***@***.***&gt;
发送时间: 2023年11月15日 10:45
收件人: Yanyutin753/googleSearch-On-Wechat ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Yanyutin753/googleSearch-On-Wechat] 企業微信上顯示不全 (Issue #1)





 
企業微信上搜索總結看不到有有超鏈接，只有文字結果
 
 但是後台看是有超鏈接的

**Comment by keney2023** [comment]
请问chatgpt要怎么样的人设才会把链接也发出来？

**Comment by keney2023** [comment]
可以了，感谢！
